<a href="https://colab.research.google.com/github/Sakshi-HC-Gowda/Data-Science-and-Gen-AI/blob/main/creditcard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving creditcard.csv to creditcard.csv

In [ ]:
df = pd.read_csv("creditcard.csv")
df

/tmp/ipykernel_1270/809931545.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("creditcard.csv")

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,2600.0,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,63588.0,7.0,0.0,1.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df.head()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
0,1.0,0.766127,45.0,Male,South,9120.0,Ownhouse,Self_Emp,Matric,2.0,0.802982,9120.0,13.0,0.0,6.0,0.0,2.0,Bad
1,0.0,0.957151,40.0,Female,South,2600.0,Ownhouse,Self_Emp,Graduate,0.0,0.121876,2600.0,4.0,0.0,0.0,0.0,1.0,Good
2,0.0,0.658180,38.0,Female,South,3042.0,Ownhouse,Self_Emp,PhD,1.0,0.085113,3042.0,2.0,1.0,0.0,0.0,0.0,Good
3,0.0,0.233810,30.0,Female,South,3300.0,Ownhouse,Self_Emp,Professional,0.0,0.036050,3300.0,5.0,0.0,0.0,0.0,0.0,Good
4,0.0,0.907239,49.0,Male,South,63588.0,Ownhouse,Self_Emp,Post-Grad,1.0,0.024926,63588.0,7.0,0.0,1.0,0.0,0.0,Good

In [ ]:
df.tail()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df.shape

(150002, 18)

In [ ]:
df.columns

Index(['NPA Status', 'RevolvingUtilizationOfUnsecuredLines', 'age', 'Gender',
       'Region', 'MonthlyIncome', 'Rented_OwnHouse', 'Occupation', 'Education',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome.1',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents', 'Good_Bad'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150002 entries, 0 to 150001
Data columns (total 18 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   NPA Status                            150000 non-null  float64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  float64
 3   Gender                                150000 non-null  object
 4   Region                                150000 non-null  object
 5   MonthlyIncome                         120269 non-null  float64
 6   Rented_OwnHouse                       150000 non-null  object
 7   Occupation                            150000 non-null  object
 8   Education                             150000 non-null  object
 9   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  float64
 10  DebtRatio                             150000 non-null  float64
 11  MonthlyIncome.1                       120269 non-null  float64
 12  NumberOfOpenCreditLinesAndLoans       150000 non-null  float64
 13  NumberOfTimes90DaysLate               150000 non-null  float64
 14  NumberRealEstateLoansOrLines          150000 non-null  float64
 15  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  float64
 16  NumberOfDependents                    146078 non-null  object
 17  Good_Bad                              150000 non-null  object
dtypes: float64(11), object(7)
memory usage: 20.6+ MB

In [ ]:
df.dtypes

NPA Status                              float64
RevolvingUtilizationOfUnsecuredLines    float64
age                                     float64
Gender                                   object
Region                                   object
MonthlyIncome                           float64
Rented_OwnHouse                          object
Occupation                               object
Education                                object
NumberOfTime30-59DaysPastDueNotWorse    float64
DebtRatio                               float64
MonthlyIncome.1                         float64
NumberOfOpenCreditLinesAndLoans         float64
NumberOfTimes90DaysLate                 float64
NumberRealEstateLoansOrLines            float64
NumberOfTime60-89DaysPastDueNotWorse    float64
NumberOfDependents                       object
Good_Bad                                 object
dtype: object

In [ ]:
df.isnull().sum()

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29733
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
MonthlyIncome.1                         29733
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3924
Good_Bad                                    2
dtype: int64

How does it work?
df.isnull()

checks:

Is the value missing?

It returns:

True
False

Then:

.sum()

counts the True values.

So:

df.isnull().sum()

means:

Count missing values in every column.

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29733
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
MonthlyIncome.1                         29733
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3924
Good_Bad                                    2
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(63420)

In [ ]:
df.duplicated().sum()

np.int64(20)

In [ ]:
df[df.duplicated()]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
7920,0.0,1.0,22.0,Male,South,820.0,Ownhouse,Self_Emp,Matric,0.0,0.0,820.0,1.0,0.0,0.0,0.0,0.0,Good
19814,0.0,1.0,68.0,Female,North,NaN,Ownhouse,Officer3,Post-Grad,0.0,0.0,NaN,2.0,0.0,0.0,0.0,0.0,Good
19987,0.0,1.0,37.0,Female,North,NaN,Ownhouse,Self_Emp,Post-Grad,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,Good
37075,0.0,1.0,23.0,Male,North,0.0,Ownhouse,Self_Emp,Matric,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Good
40396,0.0,0.0,46.0,Female,North,NaN,Ownhouse,Self_Emp,Post-Grad,0.0,0.0,NaN,5.0,0.0,0.0,0.0,0.0,Good
43095,0.0,1.0,22.0,Male,North,820.0,Ownhouse,Officer1,Post-Grad,0.0,0.0,820.0,1.0,0.0,0.0,0.0,0.0,Good
44485,0.0,1.0,22.0,Female,North,NaN,Ownhouse,Officer3,Post-Grad,98.0,0.0,NaN,0.0,98.0,0.0,98.0,0.0,Good
66276,0.0,0.0,82.0,Male,Central,NaN,Ownhouse,Self_Emp,Professional,0.0,0.0,NaN,3.0,0.0,0.0,0.0,0.0,Good
67173,0.0,0.0,87.0,Male,Central,NaN,Rented,Non-officer,Professional,0.0,0.0,NaN,4.0,0.0,0.0,0.0,0.0,Good
82357,0.0,0.0,24.0,Male,Central,NaN,Ownhouse,Self_Emp,Professional,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,Good
99854,0.0,1.0,58.0,Male,Central,NaN,Ownhouse,Non-officer,Graduate,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,Good
105018,0.0,0.0,87.0,Female,West,NaN,Rented,Self_Emp,Graduate,0.0,0.0,NaN,4.0,0.0,0.0,0.0,NaN,Good
106795,0.0,0.0,22.0,Male,West,NaN,Rented,Non-officer,Graduate,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,Good
119531,0.0,0.0,22.0,Male,West,NaN,Rented,Non-officer,Graduate,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,Good
121833,0.0,1.0,63.0,Female,East,NaN,Rented,Officer3,Post-Grad,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,Good
123531,0.0,1.0,22.0,Female,East,1000.0,Rented,Officer3,Post-Grad,0.0,0.0,1000.0,1.0,0.0,0.0,0.0,0.0,Good
124731,0.0,1.0,34.0,Female,East,NaN,Rented,Officer3,Post-Grad,98.0,0.0,NaN,0.0,98.0,0.0,98.0,0.0,Good
126176,0.0,1.0,55.0,Female,East,NaN,Rented,Self_Emp,Post-Grad,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,Good
127101,0.0,1.0,63.0,Female,East,NaN,Rented,Officer3,Post-Grad,0.0,0.0,NaN,1.0,0.0,0.0,0.0,0.0,Good
127270,0.0,1.0,32.0,Female,East,NaN,Rented,Officer1,Post-Grad,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,Good

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]

NPA Status                                  2
RevolvingUtilizationOfUnsecuredLines        2
age                                         2
Gender                                      2
Region                                      2
MonthlyIncome                           29733
Rented_OwnHouse                             2
Occupation                                  2
Education                                   2
NumberOfTime30-59DaysPastDueNotWorse        2
DebtRatio                                   2
MonthlyIncome.1                         29733
NumberOfOpenCreditLinesAndLoans             2
NumberOfTimes90DaysLate                     2
NumberRealEstateLoansOrLines                2
NumberOfTime60-89DaysPastDueNotWorse        2
NumberOfDependents                       3924
Good_Bad                                    2
dtype: int64

In [ ]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [NPA Status, RevolvingUtilizationOfUnsecuredLines, age, Gender, Region, MonthlyIncome, Rented_OwnHouse, Occupation, Education, NumberOfTime30-59DaysPastDueNotWorse, DebtRatio, MonthlyIncome.1, NumberOfOpenCreditLinesAndLoans, NumberOfTimes90DaysLate, NumberRealEstateLoansOrLines, NumberOfTime60-89DaysPastDueNotWorse, NumberOfDependents, Good_Bad]
Index: []

In [ ]:
df[df.isnull().any(axis=1)]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
6,0.0,0.305682,57.0,Female,South,NaN,Ownhouse,Self_Emp,PhD,0.0,5710.0,NaN,8.0,0.0,3.0,0.0,0.0,Good
8,0.0,0.116951,27.0,Female,South,NaN,Ownhouse,Self_Emp,Post-Grad,0.0,46.0,NaN,2.0,0.0,0.0,0.0,NaN,Good
16,0.0,0.061086,78.0,Female,South,NaN,Ownhouse,Self_Emp,Graduate,0.0,2058.0,NaN,10.0,0.0,2.0,0.0,0.0,Good
32,0.0,0.083418,62.0,Male,South,NaN,Ownhouse,Self_Emp,Graduate,0.0,977.0,NaN,6.0,0.0,1.0,0.0,0.0,Good
41,0.0,0.072898,81.0,Female,South,NaN,Ownhouse,Self_Emp,Graduate,0.0,75.0,NaN,7.0,0.0,0.0,0.0,0.0,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149984,0.0,0.037548,84.0,Male,North,NaN,Rented,Self_Emp,Professional,0.0,25.0,NaN,5.0,0.0,0.0,0.0,0,Good
149992,0.0,0.871976,50.0,Male,North,NaN,Ownhouse,Non-officer,Professional,0.0,4132.0,NaN,11.0,0.0,1.0,0.0,3,Good
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.0,NaN,18.0,0.0,1.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df[df["age"].isnull()]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df[df["Gender"].isnull()]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df[df["NPA Status"].isnull()]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df[df["age"].isnull()].index

Index([150000, 150001], dtype='int64')

In [ ]:
df[df["Gender"].isnull()].index

Index([150000, 150001], dtype='int64')

In [ ]:
df[df["NPA Status"].isnull()].index

Index([150000, 150001], dtype='int64')

In [ ]:
df.tail()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df.tail(2)

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df[df["age"].isnull()]

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
150000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,NaN
150001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,NaN

In [ ]:
df.drop(index=[150000,150001],inplace=True)

In [ ]:
df.shape

(150000, 18)

In [ ]:
df.tail()

,NPA Status,RevolvingUtilizationOfUnsecuredLines,age,Gender,Region,MonthlyIncome,Rented_OwnHouse,Occupation,Education,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome.1,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,Good_Bad
149995,0.0,0.040674,74.0,Male,North,2100.0,Ownhouse,Non-officer,Professional,0.0,0.225131,2100.0,4.0,0.0,1.0,0.0,0,Good
149996,0.0,0.299745,44.0,Male,North,5584.0,Ownhouse,Self_Emp,Professional,0.0,0.716562,5584.0,4.0,0.0,1.0,0.0,2,Good
149997,0.0,0.246044,58.0,Male,North,NaN,Rented,Officer2,Professional,0.0,3870.000000,NaN,18.0,0.0,1.0,0.0,0,Good
149998,0.0,0.000000,30.0,Male,North,5716.0,Rented,Non-officer,Professional,0.0,0.000000,5716.0,4.0,0.0,0.0,0.0,0,Good
149999,0.0,0.850283,64.0,Male,North,8158.0,Ownhouse,Self_Emp,Professional,0.0,0.249908,8158.0,8.0,0.0,2.0,0.0,0,Good

In [ ]:
df.isnull().sum()

NPA Status                                  0
RevolvingUtilizationOfUnsecuredLines        0
age                                         0
Gender                                      0
Region                                      0
MonthlyIncome                           29731
Rented_OwnHouse                             0
Occupation                                  0
Education                                   0
NumberOfTime30-59DaysPastDueNotWorse        0
DebtRatio                                   0
MonthlyIncome.1                         29731
NumberOfOpenCreditLinesAndLoans             0
NumberOfTimes90DaysLate                     0
NumberRealEstateLoansOrLines                0
NumberOfTime60-89DaysPastDueNotWorse        0
NumberOfDependents                       3924
Good_Bad                                    0
dtype: int64

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0]

MonthlyIncome         29731
MonthlyIncome.1       29731
NumberOfDependents     3924
dtype: int64

In [ ]:
monthly_mean = df["MonthlyIncome"].mean()
print(monthly_mean)

6670.221237392844

In [ ]:
df.isnull().sum().sum()

np.int64(63386)

In [ ]:
df["NumberOfDependents"].isnull().sum()

np.int64(3924)

In [ ]:
df["NumberOfDependents"] = pd.to_numeric(df["NumberOfDependents"], errors='coerce')
dep_mean = df["NumberOfDependents"].mean()
print(dep_mean)

0.7572222678605657

In [ ]:
df["NumberOfDependents"].fillna(dep_mean)

0         2.0
1         1.0
2         0.0
3         0.0
4         0.0
         ...
149995    0.0
149996    2.0
149997    0.0
149998    0.0
149999    0.0
Name: NumberOfDependents, Length: 150000, dtype: float64

In [ ]:
df["NumberOfDependents"] = pd.to_numeric(
    df["NumberOfDependents"],
    errors="coerce"
)

In [ ]:
mean_before = df["NumberOfDependents"].mean()

print("Mean before filling:", mean_before)

Mean before filling: 0.7572222678605657

In [ ]:
df_mean = df.copy()

In [ ]:
mean_value = df_mean["NumberOfDependents"].mean()

print("Mean value:", mean_value)

Mean value: 0.7572222678605657

In [ ]:
df_mean["NumberOfDependents"] = df_mean["NumberOfDependents"].fillna(mean_value)

In [ ]:
mean_after_mean = df_mean["NumberOfDependents"].mean()
print("Mean before filling:",mean_before)
print("Mean after Mean filling:",mean_after_mean)

Mean before filling: 0.7572222678605657
Mean after Mean filling: 0.7572222678605657

In [ ]:
df_median = df.copy()

In [ ]:
median_value=df_median["NumberOfDependents"].median()
print("Median value:", median_value)

Median value: 0.0

In [ ]:
df_median["NumberOfDependents"] = df_median["NumberOfDependents"].fillna(median_value)

In [ ]:
mean_after_median = df_median["NumberOfDependents"].mean()
print("Mean before filling:", mean_before)
print("Mean after Median filling:", mean_after_median)

Mean before filling: 0.7572222678605657
Mean after Median filling: 0.7374133333333334

In [ ]:
df_mode = df.copy()

In [ ]:
mode_value = df_mode["NumberOfDependents"].mode()[0]

print("Mode value:", mode_value)

Mode value: 0.0

In [ ]:
df_mode["NumberOfDependents"] = df_mode["NumberOfDependents"].fillna(mode_value)

In [ ]:
mean_after_mode = df_mode["NumberOfDependents"].mean()
print("Mean before filling:", mean_before)
print("Mean after Mode filling:", mean_after_mode)

Mean before filling: 0.7572222678605657
Mean after Mode filling: 0.7374133333333334